#!/usr/bin/env python3
"""Generate subdivision lookups from flag recipes and curated geocoder aliases.

Keep existing US/Canadian/Spanish aliases and native/English names in
subdivision_aliases.json. Recipe names for AR, BR, CH and MX are included
alongside accent-free spellings. Aliases may map to a subdivision without a
flag: FlagResolver's existing country fallback handles a missing CDN asset.
"""
import json
import unicodedata
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
OUTPUT = ROOT / 'Sources/SVGFlags/Resources/subdivisionMap.json'


def generate():
    aliases = json.loads((HERE / 'subdivision_aliases.json').read_text())
    recipes = json.loads((HERE / 'subdivisions/flags.json').read_text())['flags']
    for code, recipe in recipes.items():
        if code.split('-')[0] in ('ar', 'br', 'ch', 'mx'):
            aliases.setdefault(code, []).append(recipe['name'])
    entries = {}
    for code, names in aliases.items():
        country = code.split('-')[0]
        for name in names:
            name = unicodedata.normalize('NFC', name).strip().lower()
            plain = ''.join(c for c in unicodedata.normalize('NFD', name) if not unicodedata.combining(c))
            for spelling in {name, plain}:
                key = f'{country}:{spelling}'
                if key in entries and entries[key] != code:
                    raise ValueError(f'ambiguous subdivision name: {key}')
                entries[key] = code
    data = {'version': 1,
            '_comment': "Maps lowercased countryCode:subdivisionName to subdivision asset codes. Generated by scripts/generate_subdivision_map.py from flag recipes and scripts/subdivision_aliases.json.",
            'entries': dict(sorted(entries.items()))}
    OUTPUT.write_text(json.dumps(data, indent=2, ensure_ascii=False) + '\n')
    print(f'Wrote {len(entries)} subdivision names and aliases')


if __name__ == '__main__':
    generate()
